version: '3' 
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/data/db

  users:
    build:
      context: .
      dockerfile: services/users/Dockerfile
    depends_on:
      - mongodb  # Assure que MongoDB démarre avant users
    environment:
      - MONGO_URI=mongodb://mongodb:27018/ # Modifier la connexion
    volumes:
      - .:/backend
    ports:
      - "3001:3001"

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    depends_on:
      - users
    volumes:
      - .:/backend
    ports:
      - "3000:3000"

volumes:
  mongodb_data:
